name: 'deeplabv3plus'
log_name: 'deeplabv3plus-mobilenet'
loss_name: 'cross_entropy'
learning_rate: 0.001
optimizer_name: 'AdamW'
optimizer_eps: 1e-08
momentum: 0.0
weight_decay: 0.0
bilinear: True
batch_norm: False
class_weighting: null
export_preds_every_n_epochs: null
dropout: 0.0
backbone: 'mobilenet'
pretrained_weights: null
pretrained_backbone: False
