name: 'unet'
loss_name: 'cross_entropy'
learning_rate: 0.001
optimizer_name: 'AdamW'
optimizer_eps: 1e-08
momentum: 0.0
weight_decay: 0.0
bilinear: True
batch_norm: True
class_weighting: null
export_preds_every_n_epochs: null
dropout: 0.25
da_hflip: 0.1
