name: 'resnet_dualencoder'
log_name: 'resnet_dualencoder'
loss_name: 'cross_entropy'
learning_rate: 0.001
optimizer_name: 'AdamW'
optimizer_eps: 1e-08
momentum: 0.0
weight_decay: 0.0
class_weighting: null
export_preds_every_n_epochs: null
dropout: 0.0
