defaults:
    - _self_
    - dataset: whuohs
    - model: resnet_dualencoder

model:
    compile: False # not tested yet
    da_hflip: 0.0
    dropout: 0.0
    log_grad_norm: False
    rich_train_log: False

training: 
    # preload_path: '/mnt/data/logs/loveda2/lightning_logs/loveda-resnet_dualencoder-20240822_14-37-18/checkpoints/checkpoint-resnet_dualencoder-epoch-60-val-iou-0.533.ckpt'
    preload_path: COCO
    resume_path: '/mnt/data/logs/preloadCOCO/lightning_logs/whuohs-resnet_dualencoder-20240831_13-16-10/checkpoints/checkpoint-resnet_dualencoder-epoch-37-val-iou-0.308.ckpt'
    max_epochs: 500
    mat_mul_precision: 'high' # can be set to 'medium'|'high'|'highest'
    seed: 42
    accelerator: 'gpu'
    devices: [0]
    early_stopping: True

logging:
    project_name: ??? # required field, must be set by user
    path: '/mnt/data/logs/'
    tb_logger: True
    wb_logger: True

dataset: 
    spectral_average: False
    pca: null
    pca_out_dir: '.'
    debug: False # if true the dataset is reduced to 5 samples overall
    num_workers: 6
    normalize: False
    half_precision: False
    drop_last: False
