name: 'hyko2'
log_name: 'hyko2pca1'
basepath: '/mnt/data/datasets/hyko2'
label_set: 'semantic'
batch_size: 16
manual_seed: 42
label_def: 'hyko2-semantic_labeldef.txt'
pca: 1
pca_out_dir: '/mnt/data/datasets/hyko2/pca1'

