name: 'hyko2'
basepath: '/mnt/data/datasets/HyKo2-VIS/HyKo2-VIS_Semantic.h5'
label_set: 'semantic'
batch_size: 16
train_prop: 0.5
val_prop: 0.2
manual_seed: 42
label_def: 'hyko2-semantic_labeldef.txt'
